import type { Metadata } from 'next'
import '../globals.css'
export const metadata: Metadata = {
  title: 'Gabriel Studio',
  description: 'Generated by next + sanity',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
